spring.datasource.url=jdbc:postgresql://cloudstoragedb_uaja_user:cHt1KapkszIiaxFYAAAEiXQOwv3zhroA@dpg-d8g0ogu7r5hc73ajcje0-a/cloudstoragedb_uaja
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=5432
